# Generated by Django 2.2.5 on 2020-01-28 07:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_create', models.DateTimeField(auto_now_add=True)),
                ('datetime_update', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Advertisement title')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Description')),
            ],
            options={
                'ordering': ['datetime_create'],
            },
        ),
        migrations.CreateModel(
            name='PhotoLinks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_create', models.DateTimeField(auto_now_add=True)),
                ('datetime_update', models.DateTimeField(auto_now=True)),
                ('photo_link', models.CharField(max_length=500, verbose_name='Link on the photo')),
                ('photo_number', models.IntegerField()),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billboard.Advertisement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
